cbf = ('Palmeiras', 'Flamengo', 'Internacional', 'Grêmio', 'São Paulo','Atletico Mineiro', 'Atlético-PR', 'Cruzeiro', 'Botafogo', 'Santos', 'Bahia', 'Corinthias', 'Fluminense', 'Ceará', 'Vasco da Gama', 'Sport Recife', 'América-MG', 'Chapecoense', 'Vitória', 'Paraná')
print('=!' * 30)
print(f'Lista de times do Brasileirão: {cbf}')
print('=!' * 30)
print(f'Os 5 primeiros colocados: {cbf[:5]}')
print('!=' * 30)
print(f'Últimos 4 colocados: {cbf[16:]}')
print('=!' * 30)
print(f'Lista de times em ordem alfabética: {sorted(cbf)}')
print('=!' * 30)
position = cbf.index('Chapecoense')
print(f'Chapecoense está na {position}° Posição. ')